---
id: Url
name: Url
full: URL library
description: A library that provides URL objects and methods for manipulating URLs.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Url
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
